// Code generated by goctl. DO NOT EDIT.
// goctl {{.version}}

package types{{if .containsTime}}
import (
	"time"
){{end}}
{{.types}}

// Implement the baseRes interface.
// Add the following code to another file in the same package.
// func (r *BaseRes) IsEmpty() bool {
// 	return r.Code == "" && r.Msg == ""
// }
//
// func (r *BaseRes) GetCode() string {
// 	return r.Code
// }
//
// func (r *BaseRes) GetMsg() string {
// 	return r.Msg
// }
//
// func (r *BaseRes) SetCode(code string) {
// 	r.Code = code
// }
//
// func (r *BaseRes) SetMsg(msg string) {
// 	r.Msg = msg
// }
//
// func (r *SkipWrapRes) IsSkipWrapRes() bool {
// 	return true
// }
